name: 'Update Updater JSON'

on:
  release:
    types: [published]

jobs:
  update-updater-json:
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Create updater JSON
        id: create-json
        uses: actions/github-script@v7
        with:
          script: |
            const release = context.payload.release;
            
            // Get all assets from the release
            const { data: assets } = await github.rest.repos.listReleaseAssets({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id
            });
            
            console.log('Found assets:', assets.map(a => a.name));
            
            const platforms = {};
            
            // Find binary assets and their signatures
            for (const asset of assets) {
              let platform = null;
              let isSignature = asset.name.endsWith('.sig');
              
              if (asset.name.includes('.msi')) {
                platform = 'windows-x86_64';
              } else if (asset.name.includes('.app.tar.gz')) {
                platform = 'darwin-x86_64';
              } else if (asset.name.includes('.AppImage.tar.gz')) {
                platform = 'linux-x86_64';
              }
              
              if (platform) {
                if (!platforms[platform]) {
                  platforms[platform] = { url: '', signature: '' };
                }
                
                if (isSignature) {
                  // Download signature content
                  try {
                    const sigResponse = await fetch(asset.browser_download_url);
                    const signature = await sigResponse.text();
                    platforms[platform].signature = signature.trim();
                  } catch (error) {
                    console.error(`Failed to fetch signature for ${asset.name}:`, error);
                    platforms[platform].signature = '';
                  }
                } else {
                  platforms[platform].url = asset.browser_download_url;
                }
              }
            }
            
            // Create updater JSON
            const updaterJson = {
              version: release.tag_name,
              notes: release.body || 'New version available',
              pub_date: release.published_at,
              platforms: platforms
            };
            
            console.log('Generated updater JSON:', JSON.stringify(updaterJson, null, 2));
            
            // Write to file
            const fs = require('fs');
            fs.writeFileSync('latest.json', JSON.stringify(updaterJson, null, 2));
            
            return 'success';

      - name: Upload latest.json to release
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            const release = context.payload.release;
            const filePath = 'latest.json';
            const fileName = 'latest.json';
            
            // Read the file
            const fileContent = fs.readFileSync(filePath);
            
            // Upload as release asset
            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.id,
              name: fileName,
              data: fileContent,
              headers: {
                'content-type': 'application/json'
              }
            });
            
            console.log(`Successfully uploaded ${fileName} to release`);
            return 'success';
